add_test([=[ArenaTest.Allocation]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=ArenaTest.Allocation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ArenaTest.Allocation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ArenaTest.MultipleBlocks]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=ArenaTest.MultipleBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ArenaTest.MultipleBlocks]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ArenaTest.Reset]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=ArenaTest.Reset]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ArenaTest.Reset]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TokenTest.Size]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=TokenTest.Size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TokenTest.Size]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TokenTest.Layout]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=TokenTest.Layout]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TokenTest.Layout]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TokenTest.TextMethod]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=TokenTest.TextMethod]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TokenTest.TextMethod]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InternerTest.Deduplication]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=InternerTest.Deduplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InternerTest.Deduplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UnicodeTest.Validation]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=UnicodeTest.Validation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UnicodeTest.Validation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.BasicTokens]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.BasicTokens]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.BasicTokens]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.Operators]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.Operators]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.Operators]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.Identifiers]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.Identifiers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.Identifiers]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.Keywords]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.Keywords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.Keywords]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.Numbers]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.Numbers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.Numbers]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.Strings]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.Strings]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.Strings]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LexerTest.SkipComments]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=LexerTest.SkipComments]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LexerTest.SkipComments]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.EmptyFunction]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=ParserTest.EmptyFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.EmptyFunction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.FunctionWithParams]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=ParserTest.FunctionWithParams]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.FunctionWithParams]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParserTest.VarDecl]=]  /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests/druk_tests [==[--gtest_filter=ParserTest.VarDecl]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParserTest.VarDecl]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/druk-lang/druk-lang/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  druk_tests_TESTS ArenaTest.Allocation ArenaTest.MultipleBlocks ArenaTest.Reset TokenTest.Size TokenTest.Layout TokenTest.TextMethod InternerTest.Deduplication UnicodeTest.Validation LexerTest.BasicTokens LexerTest.Operators LexerTest.Identifiers LexerTest.Keywords LexerTest.Numbers LexerTest.Strings LexerTest.SkipComments ParserTest.EmptyFunction ParserTest.FunctionWithParams ParserTest.VarDecl)
